version: "3.8"

volumes:
  mongo-volume:

services:
  back:
    container_name: BePrimeBackend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: run
    environment:
      - CLIENT_URL=http://front:3000
    depends_on:
      - mongoDB
    ports:
      - 8080:8080
    networks:
      - network-backend
      - network-frontend

  front:
    container_name: BePrimeFrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: run
      args:
        - BACKEND_URL=http://back:8080
    environment:
      - PUBLIC_BACKEND_URL=http://back:8080
      - ORIGIN=http://localhost:3000
    depends_on:
      - back
    ports:
      - 80:80
    networks:
      - network-frontend

  mongoDB:
    container_name: BePrimeMongoDB
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=beprime-dev-user
      - MONGO_INITDB_ROOT_PASSWORD=beprime-dev-password
      - MONGO_INITDB_DATABASE=beprime-dev-db
    volumes:
      - mongo-volume:/data/db
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend: