spring:
  data:
    mongodb:
      authentication-database: admin
      username: beprime-dev-user
      password: beprime-dev-password
      database: beprime-dev-db
      port: 27017
      host: 172.19.0.2
server:
  port: 8080
  servlet:
    context-path: '/api/v1'